### ISSUE TITLE
dim(X) must have a positive length

### ISSUE THREAD

**Issue by yimi16** [ChangLab/ATACPrimerTool#4]
Hi,
I am trying to use APT to disign primer for my ATAC. It works well with test data but has some problems with my data. The information is shown  below:

> `Rscript /root/Software/biosoft/ATACPrimerTool/scripts/find_qPCR_regions.R /mnt/g/data_analysis/analysis/hela-ATAC-primer/primer_design/hela_atac_3/combined.o.coverage /mnt/g/data_analysis/analysis/hela-ATAC-primer/primer_design/hela_atac_3/combined.f9.coverage 0.8 3 /mnt/g/data_analysis/analysis/hela-ATAC-primer/primer_design/hela_atac_3/read_counts.txt /mnt/g/data_analysis/analysis/hela-ATAC-primer/primer_design/hela_atac_3 /mnt/g/data_analysis/analysis/hela-ATAC-primer/primer_design/hela_atac_3/APT_output/choosed1_peaks_qPCR_regions_corr0.8_cov3.bed` (1895)
INFO 12:17:38 | pypiper:manager:1134 > <pre>
DEBU 12:17:38 | pypiper:manager:1131 > running
DEBU 12:17:38 | pypiper:manager:1131 > psutil.Popen(pid=1895, name='sh', status='sleeping', started='12:17:37')
DEBU 12:17:38 | pypiper:manager:1131 > running
DEBU 12:17:38 | pypiper:manager:1131 > psutil.Popen(pid=1895, name='sh', status='sleeping', started='12:17:37')
Error in apply(o.coverage.data[, 5:m], 1, function(x) x/t(lib.sizes.data)) :
  dim(X) must have a positive length
Calls: t -> apply
Execution halted

The command i used is :
python pipelines/ATACPrimerTool.py -O /mnt/g/data_analysis/analysis/hela-ATAC-primer/primer_design -S hela_atac_3 -G hg19 -I /mnt/g/data_analysis/analysis/hela-ATAC-primer/bams_1 -B /mnt/g/data_analysis/analysis/hela-ATAC-primer/choosed1_peaks.bed -fasta /mnt/g/genome_index/hg19_genome/hg19.fa

Any suggestions?

**Comment by katieyost** [comment]
Hi just wanted to check on this - do you resolve this issue?

**Comment by yimi16** [comment]
Hi，I solved this problem several days ago so i closed this iusse. Thanks for your concern.

**Comment by yimi16** [comment]
> Hi just wanted to check on this - did you resolve this issue?

Hi，i solved this problem several days ago so i closed this issue. Thanks for your concern.
